name: CMake Multi-Platform Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Set up CMake
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.0'

      # Install GCC or equivalent compiler (Linux only)
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Configure the build
      - name: Configure with CMake
        run: cmake -S . -B build

      # Build the project
      - name: Build with CMake
        run: cmake --build build --config Debug

      # Debug: List output directories
      - name: List directories
        if: runner.os == 'Windows'
        run: |
          dir build
          dir build\Debug

      # Test executable on Linux and macOS
      - name: Test executable on Linux/macOS
        if: runner.os != 'Windows'
        run: ./build/morse -d ".- .-.. .-.. ---"

      # Test executable on Windows
      - name: Test executable on Windows
        if: runner.os == 'Windows'
        run: |
          if (Test-Path .\build\Debug\morse.exe) {
            .\build\Debug\morse.exe -d ".- .-.. .-.. ---"
          } else {
            echo "morse.exe not found in build\Debug"
            exit 1
          }
