name: CMake Multi-Platform Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Set up CMake
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.0'

      # Install dependencies for Linux
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Configure the build
      - name: Configure with CMake
        run: cmake -S . -B build

      # Build the project
      - name: Build with CMake
        run: cmake --build build --config Release

      # Debugging: List the build directory after building
      - name: List build directory
        run: ls -R build

      # Package the artifact for release (Windows)
      - name: Package for Windows
        if: runner.os == 'Windows'
        run: |
          echo "Checking if morse.exe exists..."
          if (Test-Path -Path build/Release/morse.exe) {
            Write-Host "morse.exe found. Creating morse-windows.zip."
            Compress-Archive -Path build/Release/morse.exe -DestinationPath build/morse-windows.zip
            Write-Host "Successfully created morse-windows.zip."
          } else {
            Write-Error "morse.exe not found in build/Release/ directory!"
            exit 1
          }
        shell: pwsh
    
      # Package the artifact for release (macOS)
      - name: Package for macOS
        if: runner.os == 'macOS'
        run: |
          echo "Checking if morse binary exists..."
          ls build || echo "Build directory is empty!"
          test -f build/morse || (echo "morse binary not found!" && exit 1)
          zip -j build/morse-macos.zip build/morse || (echo "Failed to package for macOS" && exit 1)

      # Package the artifact for release (Linux)
      - name: Package for Linux
        if: runner.os == 'Linux'
        run: |
          echo "Checking if morse binary exists..."
          ls build || echo "Build directory is empty!"
          test -f build/morse || (echo "morse binary not found!" && exit 1)
          tar -czvf build/morse-linux.tar.gz -C build morse

      # Upload the artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: morse-${{ runner.os }}
          path: |
            build/morse-windows.zip
            build/morse-macos.zip
            build/morse-linux.tar.gz

      # Debugging: List all build directory contents
      - name: List build directory contents (Debugging)
        run: |
          echo "Build directory contents:"
          ls -R build/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Download the build artifact
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          path: build

      # Debugging: List downloaded artifacts
      - name: List downloaded artifacts
        run: ls -R build

      # Create GitHub Release
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Release v${{ github.run_number }}"
          body: "Release of morse"
          draft: false
          prerelease: false

      # Upload the release assets
      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/morse-windows.zip
          asset_name: morse-windows.zip
          asset_content_type: application/zip

      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/morse-macos.zip
          asset_name: morse-macos.zip
          asset_content_type: application/zip

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/morse-linux.tar.gz
          asset_name: morse-linux.tar.gz
          asset_content_type: application/gzip
