name: CMake Multi-Platform Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Set up CMake
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.0'

      # Install dependencies for Linux
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Configure the build
      - name: Configure with CMake
        run: cmake -S . -B build

      # Build the project
      - name: Build with CMake
        run: cmake --build build --config Release

      # Package the artifact for release (OS specific)
      - name: Package for Windows
        if: runner.os == 'Windows'
        run: |
          echo "Checking if morse.exe exists..."
          if (Test-Path -Path build/Release/morse.exe) {
            Compress-Archive -Path build/Release/morse.exe -DestinationPath build/morse-windows.zip
            if (Test-Path -Path build/morse-windows.zip) {
              Write-Host "morse-windows.zip successfully created."
            } else {
              Write-Error "morse-windows.zip creation failed!"
              exit 1
            }
          } else {
            Write-Error "morse.exe not found in build/Release/ directory!"
            exit 1
          }
        shell: pwsh

      - name: Package for macOS
        if: runner.os == 'macOS'
        run: |
          if [ -f build/morse ]; then
            zip -j build/morse-macos.zip build/morse
            echo "morse-macos.zip successfully created."
          else
            echo "Error: morse executable not found!" >&2
            exit 1
          fi

      - name: Package for Linux
        if: runner.os == 'Linux'
        run: |
          if [ -f build/morse ]; then
            tar -czvf build/morse-linux.tar.gz -C build morse
            echo "morse-linux.tar.gz successfully created."
          else
            echo "Error: morse executable not found!" >&2
            exit 1
          fi

      # Upload the artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: morse-${{ matrix.os }}
          path: |
            build/morse-windows.zip
            build/morse-macos.zip
            build/morse-linux.tar.gz

      # Debug build directory contents
      - name: List Build Directory
        run: |
          echo "Listing contents of the build directory:"
          ls -R build/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Download the build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          path: build

      # Create GitHub Release
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Release v${{ github.run_number }}"
          body: "Release of Morse application."
          draft: false
          prerelease: false

      # Upload the release assets
      - name: Upload Windows Asset
        if: runner.os == 'Windows'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/morse-windows.zip
          asset_name: morse-windows.zip
          asset_content_type: application/zip

      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/morse-macos.zip
          asset_name: morse-macos.zip
          asset_content_type: application/zip

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/morse-linux.tar.gz
          asset_name: morse-linux.tar.gz
          asset_content_type: application/gzip
